-- MySQL Script generated by MySQL Workbench
-- Mon May  1 14:58:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBp247jdB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBp247jdB` ;

-- -----------------------------------------------------
-- Schema DBp247jdB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBp247jdB` ;
USE `DBp247jdB` ;

-- -----------------------------------------------------
-- Table `DBp247jdB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`users` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last` VARCHAR(45) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL DEFAULT 1,
  `lvl` INT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`contact` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`contact` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `contactmail` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`tutorials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`tutorials` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`tutorials` (
  `idtutorials` INT NOT NULL AUTO_INCREMENT,
  `catergory` INT NOT NULL,
  `description` VARCHAR(450) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `users_iduser` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idtutorials`),
  INDEX `fk_tutorials_users_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_tutorials_users`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `DBp247jdB`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`questions` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`questions` (
  `idquestions` INT NOT NULL AUTO_INCREMENT,
  `catergory` INT NOT NULL,
  `description` VARCHAR(450) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `users_iduser` INT NOT NULL,
  `answer` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idquestions`),
  INDEX `fk_tutorials_users_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_tutorials_users0`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `DBp247jdB`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`questions` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`questions` (
  `idquestions` INT NOT NULL AUTO_INCREMENT,
  `catergory` INT NOT NULL,
  `description` VARCHAR(450) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `users_iduser` INT NOT NULL,
  `answer` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idquestions`),
  INDEX `fk_tutorials_users_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_tutorials_users0`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `DBp247jdB`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`answersQ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`answersQ` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`answersQ` (
  `idanswerQ` INT NOT NULL AUTO_INCREMENT,
  `category` INT NOT NULL,
  `description` VARCHAR(450) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `questions_idquestions` INT NOT NULL,
  `users_iduser` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idanswerQ`),
  INDEX `fk_answersQ_questions1_idx` (`questions_idquestions` ASC),
  INDEX `fk_answersQ_users1_idx` (`users_iduser` ASC),
  CONSTRAINT `fk_answersQ_questions1`
    FOREIGN KEY (`questions_idquestions`)
    REFERENCES `DBp247jdB`.`questions` (`idquestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answersQ_users1`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `DBp247jdB`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBp247jdB`.`answersT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBp247jdB`.`answersT` ;

CREATE TABLE IF NOT EXISTS `DBp247jdB`.`answersT` (
  `idanswerT` INT NOT NULL AUTO_INCREMENT,
  `category` INT NOT NULL,
  `description` VARCHAR(450) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `likes` INT NOT NULL DEFAULT 0,
  `users_iduser` INT NOT NULL,
  `tutorials_idtutorials` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idanswerT`),
  INDEX `fk_answersQ_users1_idx` (`users_iduser` ASC),
  INDEX `fk_answersT_tutorials1_idx` (`tutorials_idtutorials` ASC),
  CONSTRAINT `fk_answersQ_users10`
    FOREIGN KEY (`users_iduser`)
    REFERENCES `DBp247jdB`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answersT_tutorials1`
    FOREIGN KEY (`tutorials_idtutorials`)
    REFERENCES `DBp247jdB`.`tutorials` (`idtutorials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
